project:
  type: book
language: _language-ko.yml


book:
  title: "SVH Neurology Code, Stats & AI"
  page-footer: "The Catholic University of Korea, ST. Vincent’s Hospital, Department of Neurology" 
  author:
  - name: "임상 데이터 과학팀"
    affiliation: 
      - name: 성빈센트병원, 신경과
        city: Suwon-si
        state: Gyeonggi-do
        country: Republic of Korea
        url: https://www.cmcvincent.or.kr/page/main
  reader-mode: true
  repo-url: "https://github.com/koseokbum/clinical-data-science"
  # cover-image: "images/cds.png"
  sidebar:
    logo: "images/cds.svg"
  chapters:
    - index.qmd
    - part: "R 언어의 기초: 가급적 learning curve를 완만하게"
      chapters:
        - setting-up.qmd
        - names-values.qmd
        - vectors.qmd
        - dataframe.qmd
        - factors.qmd
        - condition-function.qmd
        - packages.qmd
        - formula.qmd
    - part: tidyverse.qmd
      chapters:
        - tidydata.qmd
        - tidyr.qmd
        - dplyr.qmd
        - dplyr-exercise.qmd
        - tidyselection.qmd
        - relational-dplyr.qmd
        - windowing.qmd
        - stringr.qmd
    - part: visualize.qmd
      chapters: 
        - ggplot2.qmd

    - part: "의학 통계"
      chapters: 
        # - basic-stats.qmd
        - descriptive.qmd
        - gtsummary-descriptive.qmd
        - clt.qmd
    - part: "Tidymodels을 사용한 통계 분석"
      chapters:
        - infer.qmd

    - references.qmd


bibliography: references.bib
lightbox: true
filters: 
  - style-text
engine: knitr

format:
  live-html:
    theme:
      light: cosmo
      dark: darkly
    code-link: true




