project:
  type: book
language: _language-ko.yml
book:
  title: 'SVH Neurology Code, Stats & AI (with R)'
  page-footer: "The Catholic University of Korea, ST. VINCENT'S HOSPITAL, Department of Neurology" 
  author: 
  - name: "sbko"
    affiliation: 
      - name: 성빈센트병원, 신경과
        city: Suwon-si
        state: Gyeonggi-do
        country: Republic of Korea
        url: https://www.cmcvincent.or.kr/page/main
  reader-mode: true
  downloads: "pdf"
  output-file: "R-language-for-neurology"
  repo-url: "https://github.com/koseokbum/clinical-data-science"
  cover-image: "images/cds.png"
  sidebar:
    logo: "images/cds.svg"
    collapse-level: 1

  chapters:
    - index.qmd
    - part: basic-r.qmd
      chapters:
        - setting-up.qmd
        - names-values.qmd
        - vectors.qmd
        - dataframe.qmd
        - factors.qmd
        - condition-function.qmd
        - packages.qmd
        - pipes.qmd
    - part: tidyverse.qmd
      chapters:
        - tidydata.qmd
        - tidyr.qmd
        - dplyr.qmd
        - dplyr-exercise.qmd
        - tidyselection.qmd
        - relational-dplyr.qmd
        - windowing.qmd
        - stringr.qmd
        - regex.qmd
        - lubridate.qmd
        - janitor.qmd
    - part: data-visualization.qmd
      chapters: 
        - ggplot2.qmd
        - ggplot2-colors.qmd
        - stats.qmd
        - factor-order.qmd
        - plot-customizing.qmd
        - stat-plots.qmd
        - patchwork.qmd
    # - part: "의학 통계"
    #   chapters: 
        # - basic-stats.qmd
        # - descriptive.qmd
        # - gtsummary-descriptive.qmd
        # - clt.qmd          p
    - part: rstats.qmd
      chapters:
        - formula.qmd
        - broom.qmd
        - p-value.qmd
        # - simpson.qmd
        - two-sample-means.qmd
        - correlation.qmd
        - sum-squared.qmd
        - one-anova.qmd
        - two-anova.qmd
        # - moderndive.qmd   
        - contingency.qmd
        - chisq.qmd
        - diagnostic.qmd
        - least-square.qmd
        - terms.qmd
        - logistic.qmd
        - infer-package.qmd
    - part: notebook.qmd
      chapters:
        - computational-notebook.qmd

    - references.qmd


bibliography: references.bib
lightbox: true
filters: 
  - style-text
engine: knitr

format:
  live-html:
    grid:
      sidebar-width: 400px
    code-link: true
    toc-depth: 4
    css: css/styles.css
    theme:
      light: [united] 
      dark: darkly
  # pdf:
  #   pdf-engine: xelatex
  #   include-in-header: hangul.tex
  #   toc: true
  #   number-sections: true
  #   highlight-style: github
  #   geometry:
  #     - top=30mm
  #     - left=20mm
  #     - heightrounded
  #   code-block-border-left: "#D3D3D3"

    

  
  




