project:
  type: book
language: _language-ko.yml


book:
  title: 'SVH Neurology Code, Stats & AI (with R)'
  page-footer: "The Catholic University of Korea, ST. VINCENT'S HOSPITAL, Department of Neurology" 
  author:
  - name: "임상 데이터 과학"
    affiliation: 
      - name: 성빈센트병원, 신경과
        city: Suwon-si
        state: Gyeonggi-do
        country: Republic of Korea
        url: https://www.cmcvincent.or.kr/page/main
  reader-mode: true
  downloads: "pdf"
  output-file: "R-language-for-neurology"
  repo-url: "https://github.com/koseokbum/clinical-data-science"
  # cover-image: "images/cds.png"
  sidebar:
    logo: "images/cds.svg"
  chapters:
    - index.qmd
    - part: "R 언어의 기초: 가급적 learning curve를 완만하게"
      chapters:
        - setting-up.qmd
        - names-values.qmd
        - vectors.qmd
        - dataframe.qmd
        - factors.qmd
        - condition-function.qmd
        - packages.qmd
        - formula.qmd
        - pipes.qmd
    - part: tidyverse.qmd
      chapters:
        - tidydata.qmd
        - tidyr.qmd
        - dplyr.qmd
        - dplyr-exercise.qmd
        - tidyselection.qmd
        - relational-dplyr.qmd
        - windowing.qmd
        - stringr.qmd
        - regex.qmd
        - lubridate.qmd
        - janitor.qmd
    - part: data-understanding.qmd
      chapters: 
        - ggplot2.qmd
        - ggplot2-colors.qmd
        - stats.qmd
        - factor-order.qmd
        - plot-customizing.qmd
        - stat-plots.qmd
    # - part: "의학 통계"
    #   chapters: 
        # - basic-stats.qmd
        # - descriptive.qmd
        # - gtsummary-descriptive.qmd
        # - clt.qmd
    - part: "Tidymodels를 사용한 통계 분석"
      chapters:
        # - moderndive.qmd   
        - infer-package.qmd
    - references.qmd


bibliography: references.bib
lightbox: true
filters: 
  - style-text
engine: knitr

format:
  live-html:
    code-link: true
    toc-depth: 4
    theme:
      light: [united] 
      dark: darkly
  pdf:
    latex-engine: xelatex
    include-in-header: hangul.tex
    toc: true
    number-sections: true
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    code-block-border-left: "#D3D3D3"

    

  
  




